# Generated by Django 3.2.2 on 2021-07-13 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210713_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('site', models.SlugField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserCommunicationNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=128)),
                ('communication_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.communicationnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='communications',
            field=models.ManyToManyField(blank=True, through='users.UserCommunicationNetwork', to='users.CommunicationNetwork'),
        ),
    ]
