# Generated by Django 3.2.2 on 2021-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210713_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationnetwork',
            name='site',
            field=models.URLField(max_length=128),
        ),
    ]
