# Generated by Django 3.2.2 on 2021-07-14 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20210714_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Объект избранного', 'verbose_name_plural': 'Объекты избранного'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='users.user', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Название рецепта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_cooking',
            field=models.PositiveIntegerField(verbose_name='templatesВремя приготовления'),
        ),
    ]
