# Generated by Django 3.2.2 on 2021-07-21 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20210717_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='MielTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(verbose_name='Завтрак')),
                ('lunch', models.BooleanField(verbose_name='Обед')),
                ('dinner', models.BooleanField(verbose_name='Ужин')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='RecipeMielTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miel_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.mieltime')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Период приема шищи',
                'verbose_name_plural': 'Периоды приема пищи',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='miel_time',
            field=models.ManyToManyField(through='recipes.RecipeMielTime', to='recipes.MielTime', verbose_name='Время приема пищи'),
        ),
    ]
