# Generated by Django 3.2.2 on 2021-07-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210721_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MielTime',
            new_name='MealTime',
        ),
        migrations.RenameModel(
            old_name='RecipeMielTime',
            new_name='RecipeMealTime',
        ),
        migrations.RenameField(
            model_name='recipemealtime',
            old_name='miel_time',
            new_name='meal_time',
        ),
    ]
