# Generated by Django 3.2.2 on 2021-07-21 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210721_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtime',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='mealtime',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='mealtime',
            name='lunch',
        ),
        migrations.AddField(
            model_name='mealtime',
            name='name_english',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Наименование на английском языке'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealtime',
            name='name_russian',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Наименование на русском языке'),
            preserve_default=False,
        ),
    ]
