# Generated by Django 3.2.2 on 2021-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210721_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtime',
            name='name_english',
            field=models.CharField(max_length=128, unique=True, verbose_name='Наименование на английском языке'),
        ),
    ]
