# Generated by Django 3.2.2 on 2021-08-01 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0017_tag_tagsrecipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagsrecipe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagsrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='tagsrecipe',
            name='tag',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='miel_time',
            field=models.ManyToManyField(related_name='rmt', through='recipes.RecipeMealTime', to='recipes.MealTime', verbose_name='Время приема пищи'),
        ),
        migrations.AlterField(
            model_name='recipemealtime',
            name='meal_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmt_mt', to='recipes.mealtime'),
        ),
        migrations.AlterField(
            model_name='recipemealtime',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmt_r', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_author', to=settings.AUTH_USER_MODEL, verbose_name='Рецепт'),
        ),
        migrations.AlterUniqueTogether(
            name='recipemealtime',
            unique_together={('recipes', 'meal_time')},
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagsRecipe',
        ),
    ]
