# Generated by Django 3.2.2 on 2021-08-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20210801_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipemealtime',
            options={'ordering': ['-recipes'], 'verbose_name': 'Период приема шищи', 'verbose_name_plural': 'Периоды приема пищи'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='miel_time',
            new_name='meal_time',
        ),
    ]
