# Generated by Django 3.2.2 on 2021-08-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210802_0817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipes', 'ingredient')},
        ),
    ]
